### Get all text identifiers 
GET http://127.0.0.1:8080/
Accept: application/json

### Retrieve a particular text slice (first paragraph of chapter 1)
GET http://127.0.0.1:8080/julesverne?begin=1615&end=1826

### Retrieve a particular text slice (with extension) (first paragraph of chapter 1)
GET http://127.0.0.1:8080/julesverne.txt?begin=1615&end=1826

### Retrieve a particular text slice (char-schema syntax like in RFC5147)
GET http://127.0.0.1:8080/julesverne?char=1615,1826

### Retrieve a particular text slice (line-schema syntax like in RFC5147)
GET http://127.0.0.1:8080/julesverne?line=500,510

### Retrieve a particular text slice (API2)
GET http://127.0.0.1:8080/api2/julesverne/1615,1826

### Receive the last 200 characters
GET http://127.0.0.1:8080/julesverne?begin=-200

### Retrieve a particular text slice (char-schema syntax like in RFC5147)
GET http://127.0.0.1:8080/julesverne?char=-200

### Error when text does not exist
GET http://127.0.0.1:8080/doesnotexist

### Get metadata (size, last modification time)
GET http://127.0.0.1:8080/stat/julesverne

### Get metadata (API2)
GET http://127.0.0.1:8080/api2/julesverne/info.json

### Add a new text (note that this adds a directory test to place it in)
POST http://127.0.0.1:8080/test/hello
Content-Type: text/plain

你好世界！

### Retrieve the full text
GET http://127.0.0.1:8080/test/hello

### Retrieve the first two characters
GET http://127.0.0.1:8080/test/hello?char=0,2

### Retrieve the middle two characters
GET http://127.0.0.1:8080/test/hello?char=2,4

### Retrieve the last two characters
GET http://127.0.0.1:8080/test/hello?char=-2

### Retrieve a particular text slice (API2)
GET http://127.0.0.1:8080/api2/test|hello/2,4

### Retrieve a particular text slice (API2, with extension)
GET http://127.0.0.1:8080/api2/test|hello.txt/2,4

### Error when offset out of range 
GET http://127.0.0.1:8080/test/hello?char=5,34

### length check
GET http://127.0.0.1:8080/test/hello?char=2,4&length=2

### length check (fail)
GET http://127.0.0.1:8080/test/hello?char=2,4&length=2

### MD5 check
GET http://127.0.0.1:8080/test/hello?char=2,4&md5=c086b3008aca0efa8f2ded065d6afb50

### MD5 check (fail)
GET http://127.0.0.1:8080/test/hello?char=2,4&md5=c086b3008aca0efa8f2ded065d6afb51

### Delete a text 
DELETE http://127.0.0.1:8080/test/hello

